
import { Tool, ToolCategory } from './types';

export const TOOLS: Tool[] = [
  {
    id: 'selenium-base',
    name: 'Selenium WebDriver',
    category: ToolCategory.AUTOMATION,
    description: 'The industry standard for web browser automation. Supports multiple languages and browsers.',
    url: 'https://www.selenium.dev/',
    howToUse: 'Install the web driver for your browser, use the Selenium library in Java, Python, or JS to script browser actions.',
    frameworks: ['Java', 'Python', 'C#', 'JavaScript'],
    tags: ['Traditional', 'Web', 'Cross-browser', 'Open Source'],
    isPaid: false,
    isOpenSource: true,
    agentStrategy: 'Use Selenium as the foundation for an AI agent by wrapping its locator strategies with an LLM that can heal broken selectors in real-time.',
    version: '4.21.0'
  },
  {
    id: 'playwright-base',
    name: 'Playwright',
    category: ToolCategory.AUTOMATION,
    description: 'Modern end-to-end testing for modern web apps. Fast, reliable, and capable of testing across all modern engines.',
    url: 'https://playwright.dev/',
    howToUse: 'Use the Playwright CLI to generate tests or script them in TypeScript/JS. Use auto-waiting for stable execution.',
    frameworks: ['TypeScript', 'JavaScript', 'Python', 'Java'],
    tags: ['Traditional', 'Web', 'Fast', 'Auto-wait', 'Modern'],
    isPaid: false,
    isOpenSource: true,
    agentStrategy: 'Integrate with ZeroStep or similar AI wrappers to turn Playwright scripts into natural language agents that adapt to UI changes.',
    version: '1.44.0'
  },
  {
    id: 'cypress-base',
    name: 'Cypress',
    category: ToolCategory.AUTOMATION,
    description: 'Fast, easy and reliable testing for anything that runs in a browser.',
    url: 'https://www.cypress.io/',
    howToUse: 'Install via npm, write tests in JavaScript/TypeScript directly in your web project context.',
    frameworks: ['JavaScript', 'TypeScript'],
    tags: ['Traditional', 'Web', 'Developer-friendly', 'E2E'],
    isPaid: false,
    isOpenSource: true,
    agentStrategy: 'Utilize Cypress experimental features and AI plugins to create a self-correcting test suite that learns from previous execution failures.',
    version: '13.10.0'
  },
  {
    id: 'appium-base',
    name: 'Appium',
    category: ToolCategory.AUTOMATION,
    description: 'An open-source project and ecosystem of software tools to facilitate UI automation of many app platforms (Mobile, Desktop).',
    url: 'http://appium.io/',
    howToUse: 'Set up the Appium server and use the client library to interact with native, hybrid, or mobile web apps.',
    frameworks: ['Java', 'Python', 'JavaScript', 'C#'],
    tags: ['Traditional', 'Mobile', 'iOS', 'Android', 'Desktop'],
    isPaid: false,
    isOpenSource: true,
    agentStrategy: 'Pair Appium with a visual AI model to identify mobile elements that lack accessibility IDs, allowing for more robust cross-platform mobile agents.',
    version: '2.5.4'
  },
  {
    id: 'promptfoo',
    name: 'Promptfoo',
    category: ToolCategory.EVALUATION,
    description: 'Test your LLM prompts, models, and RAGs. Evaluate quality, security, and performance using test cases defined in YAML/JSON.',
    url: 'https://www.promptfoo.dev/',
    howToUse: 'Define test cases in YAML/JSON, run benchmarks via CLI to compare outputs across different models.',
    frameworks: ['Node.js', 'Python', 'CI/CD Pipelines'],
    tags: ['AI-Native', 'LLM Testing', 'RAG', 'Red-teaming', 'Evaluation'],
    isPaid: false,
    isOpenSource: true,
    agentStrategy: 'Use Promptfoo as a gatekeeper in CI/CD. When a prompt changes, the "Agent" automatically triggers a regression suite of LLM evals and blocks deployment if scores drop.',
    version: '0.62.1'
  },
  {
    id: 'deepeval',
    name: 'DeepEval',
    category: ToolCategory.EVALUATION,
    description: 'The unit testing framework for LLMs. Uses metrics like faithfulness, relevancy, and hallucination to validate outputs.',
    url: 'https://www.confident-ai.com/',
    howToUse: 'Integrate into Pytest suites. Define metrics and thresholds for your RAG or LLM application outputs.',
    frameworks: ['Python', 'Pytest', 'LangChain'],
    tags: ['AI-Native', 'LLM Unit Tests', 'Metrics', 'Hallucination Check'],
    isPaid: false,
    isOpenSource: true,
    agentStrategy: 'Create an autonomous evaluation loop where DeepEval periodically scrapes production logs and runs synthetic test cases to detect drift automatically.',
    version: '0.21.31'
  },
  {
    id: 'testim',
    name: 'Testim (by Tricentis)',
    category: ToolCategory.AUTOMATION,
    description: 'AI-powered test automation that focuses on stability and fast authoring through smart locators.',
    url: 'https://www.testim.io/',
    howToUse: 'Record tests in the browser; Testim’s AI analyzes the DOM and creates robust locators that don’t break when the UI changes.',
    frameworks: ['Web', 'Mobile', 'Salesforce'],
    tags: ['AI-Enhanced', 'Self-healing', 'Low-code', 'No-code'],
    isPaid: true,
    isOpenSource: false,
    agentStrategy: 'Enable the "Auto-improve" agent which monitors test runs and automatically updates locators in the background without manual intervention.',
    version: 'v2024.1'
  },
  {
    id: 'testrigor',
    name: 'testRigor',
    category: ToolCategory.AUTOMATION,
    description: 'Write tests in plain English. The AI engine interprets your instructions and interacts with the app like a human.',
    url: 'https://testrigor.com/',
    howToUse: 'Write steps like "click on login button". The AI interprets the UI and executes the actions.',
    frameworks: ['Web', 'Mobile', 'API', 'Desktop'],
    tags: ['AI-Native', 'Generative AI', 'NLP', 'Enterprise'],
    isPaid: true,
    isOpenSource: false,
    agentStrategy: 'Connect testRigor to your documentation. The agent can "read" new feature specs and generate the corresponding test cases automatically.',
    version: 'v5.2'
  },
  {
    id: 'applitools',
    name: 'Applitools',
    category: ToolCategory.VISUAL,
    description: 'The industry standard for Visual AI. Validates visual correctness across all devices and browsers using human-like perception.',
    url: 'https://applitools.com/',
    howToUse: 'Integrate the SDK into existing Selenium, Playwright, or Cypress scripts for "Eyes" verification.',
    frameworks: ['Playwright', 'Cypress', 'Selenium', 'Appium'],
    tags: ['AI-Native', 'Visual Testing', 'UX', 'Cross-device'],
    isPaid: true,
    isOpenSource: false,
    agentStrategy: 'Set up an autonomous "Visual Guard" that runs against production every hour, flagging only visual changes that would actually be visible to a user.',
    version: 'Eyes SDK v1.29'
  },
  {
    id: 'percy',
    name: 'Percy (by BrowserStack)',
    category: ToolCategory.VISUAL,
    description: 'All-in-one visual testing and review platform. Seamlessly integrates visual diffing into your existing CI/CD flow.',
    url: 'https://percy.io/',
    howToUse: 'Snap screenshots during your functional tests and upload them to Percy for diffing.',
    frameworks: ['Cypress', 'Playwright', 'Storybook', 'Jenkins'],
    tags: ['AI-Enhanced', 'Visual Regression', 'CI/CD', 'Web'],
    isPaid: true,
    isOpenSource: false,
    agentStrategy: 'Automate visual regression reviews by using Percy’s "Auto-Approve" features for trusted UI component libraries.',
    version: 'v3.1.0'
  }
];
